### PR TITLE
Fix setting root CA certificate for TLS clients

### LINKED ISSUE #82: Unable to test plugins with TLS channel on Windows
**Description**
When starting an example plugin (`rand`) on Windows with TLS enabled, error prevents plugin from working. Plugin complains that system root certificates are unavailable on Windows.

**Steps to reproduce**
1. build example plugin for windows
```bash
cd examples/snap-plugin-collector-rand
GOOS=windows GOARCH=386 go build
```
2. launch example plugin with TLS enabled
```bash
snap-plugin-collector-rand.exe "{\"CertPath\":\"libtest-srv.crt\",\"KeyPath\":\"libtest-srv.key\"}
```

**Observed outcome**
Plugin throws an error:
`panic: unable to read root CAs: crypto/x509: system root pool is not available on Windows`

**Expected outcome**
Plugin starts without issues.

**Remarks**
I understand that golang doesn't have complete support for root certificates on Windows, according to issue golang/go#16736. 
It would be better to add support for explicitly specified root certificates for all plugins based on this library, e.g.: `RootCertPaths: \"libtest-CA.crt;clients-use-this.crt\"`.

### PR DESCRIPTION
**Pull request by marcintao**
- fixes #82,
- plugins are now accepting another run-time argument, RootCertPaths;
- ... being a list of fs paths (to directory or file), this enables plugins to use explicitly specified root certificates to validate client TLS certificates.
- to test this feature just add another argument to invocation of plugin binary, e.g.: `"RootCertPaths":"/tmp/first-root.crt:/tmp/second-root.crt:/tmp/many-roots-dir/"`

**Tests executed**
* developer tests,
* unit tests available in source tree,
* added unit tests to cover new functionality.

### CODE REVIEW

**Comment by andrzej-k** [comment]
Is there any documentation that needs to be updated to indicate how to use new plugin arg?

File: v1/plugin/grpc_tls_test.go [hunk 1]
```diff
@@ -175,15 +127,8 @@ func newGrpcOptsBuilder() *grpcOptsBuilder {
...
-	retCode := m.Run()
-	tearDownTestMain()
-	os.Exit(retCode)
-}
-
 func TestIncorrectPluginArgsFail(t *testing.T) {
-	FocusConvey("Intending to start secure plugin server", t, func() {
+	Convey("Intending to start secure plugin server", t, func() {
 		setUpSecureTestcase(true, true)
 		Convey("omitting Cert Path from arguments will make plugin fail", func() {
```
Comment (marcintao) [inline v1/plugin/grpc_tls_test.go]: Not here - this relates to server's TLS certificate. System cert pool provides set of trusted certificates which are use to validate **client's** certificate.

**Comment by marcintao** [comment]
@andrzej-k there is no documentation now that needs to be updated. This PR fixes an issue that relates to plugin internal interface. I expect that documentation will get added once plugin diagnostics effort is concluded.
